language: node_js
node_js:
- '6'
env:
  matrix:
    secure: PQ39PwnRF0cjmVk+zwKmzV5oG+8NgImOukQXh7o7QMbFevgj23GttnfYUGJ7cIH4S2SLcrFL8L4i3FNofH5hPsCgdUvBbWye8uSXfCce+aop6St4EbbUos1RBja73soPIX1UVJ91CyAw759N2Tx+zvZSyOj07NKaaGaVpCAE4fdIPAB42lmNncY8/s2WbiKSFrZ76H5UAdXDhg+xecmY39g47hjbkr7weK9L8EIe5jXwQdnkWnNaQL8IiTTVC/qgFA1LRR5sy4FMsoZ3KFoQQNGixcgbg3TMU5UN2FJgNBXSvfqH/WgEcEWzLmgxr423Z3CKFKT0facTd3pWIl/ncgYADCsgcpN4XESkHXi7VcMDyr/zzDwKZeEnHhayujki49Iru1m9RvomyAeriHw/g5OY9z47UioXVJRY8PfjOB7sJD4b1IIxPb87yYk8sXDrbR/WOX8VieZ+5iyvnk7YsZlgFwubfgM14ZFBzUGOO/iaId43nPVbc4ZQfVeQLhRdA7aEi4Mpb2sYcf57Vf7d3Ii7XXeCcR+JPe7tt/QT4+Xu0Z6OZq9jOkJE1gmIzpg8iHlaQn1FeO238sHIxkzHcMJDVcxWDFJsxgsta4VFAmAC8EL/ZPKntPtjys1Yes3rrOtJnTKLAL0EaKtfVits542bthKADk1l04BGdajI27s=
