language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: qscE4Z9hcbAfQrfYrCNgDLU3EslnjV6zK4KP6KhUA3whcLgSPyJ6QY8mpS7hH7zgu9l8QGFXQOe9+iqE4l/0LtZA9StC8kb0m2Lo5qxbr/Sbv1/VRwvgQWulw10KOaskMV5XdbuDe6j1PM9E8zOb/KPOR+RSfvtQyR2SKCs6no6/MoBMhiuuAfwKVcNGlHr/mB6UsctosKJTYs4ZSdI0Cgt3QWyq6UVfzBX6sO5OjzRaYDLwAR9ScwmIo1Jd7z7SyxgXBOe1kjX9wo3FsDwhZv5H3hqZ8miwk3xSQXsyGnXLdUnppunMyPaZpyXgW4duAl9r7Fixxf9I+IkQYBjGBeoZk8V7bW0f0r8TVdohOASJwagAaBre5JHdkRrLcYxAwMn5vqVcjlCOk9YGELoYdFQ2otHiAmiMK34y4nqP+eg19DYtk9EdZMNRW/otdRQxCCgKuep0fg3N/DDafiGiiOnb/9RwFp8q+5LDkIkayWlF93WnWRC2Q3Ml3Ctmxby6qPTF8YO5BKgoWKdiG/Fqp1yxhFaO94yJPVvDb/bxjBQFZHzC2Xp2K3k+qwq1pG+rsvfSnPRP0c6bNS9TuFWRnruKb4kGi1MUtWCkyEDLa0zbt/Xfw0WscI4D/TdDvMz6nwh1WyiFGNOOWWOw1SKkrXE8bmt/vfHL4PZr8YngWN0=
  app: greg-slackbot
